[book]
title = "Rust 参考手册"
author = "The Rust Project Developers"
translator = "rust-lang-cn, zzy"

[output.html]
additional-css = ["theme/reference.css"]
additional-js = ["language.js"]
git-repository-url = "https://github.com/rust-lang-cn/reference-cn"
