[book]
title = "Rust 参考手册"
author = "The Rust Project Developers"
translator = "rust-lang-cn, zzy"

[output.html]
additional-css = ["theme/reference.css"]
git-repository-url = "https://github.com/rust-lang/reference/"

[output.html.redirect]
"/expressions/enum-variant-expr.html" = "struct-expr.html"
